apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomodiaperson
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /health/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfomodiaperson.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  envFrom:
    - secret: syfomodiaperson-session-key
  webproxy: true
  ingresses:
    - "https://syfomodiaperson.intern.nav.no"
  env:
    - name: NAIS_CONTEXT
      value: 'prod'
    - name: NODE_ENV
      value: "production"
    - name: REDIS_HOST
      value: "syfomodiaperson-redis"
    - name: AUTH_REDIRECT_URI
      value: "https://syfomodiaperson.intern.nav.no/oauth2/callback"
    - name: FASTLEGEREST_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.fastlegerest"
    - name: FASTLEGEREST_HOST
      value: "fastlegerest.intern.nav.no"
    - name: INTERNARBEIDSFLATEDECORATOR_HOST
      value: "internarbeidsflatedecorator.intern.nav.no"
    - name: ISDIALOGMELDING_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmelding"
    - name: ISDIALOGMELDING_HOST
      value: "isdialogmelding.intern.nav.no"
    - name: ISDIALOGMOTE_AAD_APP_CLIENT_ID
      value: "4898e614-e73d-4067-aafd-5afc2254c6b6"
    - name: ISDIALOGMOTE_HOST
      value: "isdialogmote.intern.nav.no"
    - name: ISDIALOGMOTEKANDIDAT_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isdialogmotekandidat"
    - name: ISDIALOGMOTEKANDIDAT_HOST
      value: "isdialogmotekandidat.intern.nav.no"
    - name: ISNARMESTELEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isnarmesteleder"
    - name: ISNARMESTELEDER_HOST
      value: "isnarmesteleder.intern.nav.no"
    - name: ISOPPFOLGINGSTILFELLE_HOST
      value: "isoppfolgingstilfelle.intern.nav.no"
    - name: ISOPPFOLGINGSTILFELLE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.isoppfolgingstilfelle"
    - name: ISPENGESTOPP_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ispengestopp"
    - name: ISPENGESTOPP_HOST
      value: "ispengestopp.intern.nav.no"
    - name: ISPERSONOPPGAVE_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.ispersonoppgave"
    - name: ISPERSONOPPGAVE_HOST
      value: "ispersonoppgave.intern.nav.no"
    - name: MODIACONTEXTHOLDER_HOST
      value: "modiacontextholder.intern.nav.no"
    - name: SYFOBEHANDLENDEENHET_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_HOST
      value: "syfobehandlendeenhet.intern.nav.no"
    - name: SYFOMOTEADMIN_AAD_APP_CLIENT_ID
      value: "df2c236f-d109-4999-b255-206757b2f8b4"
    - name: SYFOMOTEADMIN_HOST
      value: "syfomoteadmin.intern.nav.no"
    - name: SYFOMOTEBEHOV_AAD_APP_CLIENT_ID
      value: "54f7befe-1d6b-45de-a718-a47de79c4239"
    - name: SYFOMOTEBEHOV_HOST
      value: "syfomotebehov.intern.nav.no"
    - name: SYFOOPPFOLGINGSPLANSERVICE_AAD_APP_CLIENT_ID
      value: "9eae3413-a2e3-4b5b-bb56-f5fa1e737110"
    - name: SYFOOPPFOLGINGSPLANSERVICE_HOST
      value: "syfooppfolgingsplanservice.intern.nav.no"
    - name: SYFOPERSON_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoperson"
    - name: SYFOPERSON_HOST
      value: "syfoperson.intern.nav.no"
    - name: SYFOSMREGISTER_AAD_APP_CLIENT_ID
      value: "6d760b8b-6378-4534-864f-e07747359481"
    - name: SYFOSMREGISTER_HOST
      value: "syfosmregister.intern.nav.no"
    - name: SYKEPENGESOKNAD_BACKEND_AAD_APP_CLIENT_ID
      value: "prod-gcp.flex.sykepengesoknad-backend"
    - name: SYKEPENGESOKNAD_BACKEND_HOST
      value: "flex-intern-gateway.intern.nav.no"
    - name: SYFOTILGANGSKONTROLL_AAD_APP_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_HOST
      value: "syfo-tilgangskontroll.intern.nav.no"
    - name: SYFOVEILEDER_AAD_APP_CLIENT_ID
      value: "prod-gcp.teamsykefravr.syfoveileder"
    - name: SYFOVEILEDER_HOST
      value: "syfoveileder.intern.nav.no"
