// Matches data-cy attributes in components
export const selectors = {
  avlysMoteKnapp: "avlysMoteKnapp",
  endreMoteKnapp: "endreMoteKnapp",
  sendAvlysningKnapp: "sendAvlysningKnapp",
  sendEndringKnapp: "sendEndringKnapp",
  begrunnelseArbeidstakerKnapp: "begrunnelseArbeidstakerKnapp",
  begrunnelseArbeidstakerTextArea: "begrunnelseArbeidstakerTextArea",
  begrunnelseArbeidsgiverKnapp: "begrunnelseArbeidsgiverKnapp",
  begrunnelseArbeidsgiverTextArea: "begrunnelseArbeidsgiverTextArea",
  begrunnelseBehandlerKnapp: "begrunnelseBehandlerKnapp",
  begrunnelseBehandlerTextArea: "begrunnelseBehandlerTextArea",
  situasjonTextArea: "situasjonTextArea",
  konklusjonTextArea: "konklusjonTextArea",
  arbeidstakersOppgaveTextArea: "arbeidstakersOppgaveTextArea",
  arbeidsgiversOppgaveTextArea: "arbeidsgiversOppgaveTextArea",
  fritekstArbeidsgiverTextArea: "fritekstArbeidsgiverTextArea",
  fritekstArbeidstakerTextArea: "fritekstArbeidstakerTextArea",
  fritekstBehandlerTextArea: "fritekstBehandlerTextArea",
  fritekstArbeidsgiverKnapp: "fritekstArbeidsgiverKnapp",
  fritekstArbeidstakerKnapp: "fritekstArbeidstakerKnapp",
  fritekstBehandlerKnapp: "fritekstBehandlerKnapp",
  forhandsvisningModal: "ForhåndsvisningModal",
  nyttMoteplanleggerMote: "nyttMoteplanleggerMote",
  nyttDM2Mote: "nyttDM2Mote",
};
