const ANDRE_ARBEIDSFORHOLD = "ANDRE_ARBEIDSFORHOLD";
const SELVSTENDIG_NAERINGSDRIVENDE = "SELVSTENDIG_NAERINGSDRIVENDE";
const SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA =
  "SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA";
const JORDBRUKER_FISKER_REINDRIFTSUTOEVER =
  "JORDBRUKER_FISKER_REINDRIFTSUTOEVER";
const FRILANSER = "FRILANSER";
export const ANNET = "ANNET";

export const fields = [
  ANDRE_ARBEIDSFORHOLD,
  SELVSTENDIG_NAERINGSDRIVENDE,
  SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA,
  JORDBRUKER_FISKER_REINDRIFTSUTOEVER,
  FRILANSER,
  ANNET,
];

const inntektskildetyper = fields.map((annenInntektskildeType) => {
  return {
    annenInntektskildeType,
  };
});

export default inntektskildetyper;
