export const NAERMESTE_LEDER = 'NAERMESTE_LEDER';
export const TIDSLINJEN = 'TIDSLINJEN';
export const MOETEPLANLEGGER = 'MOETEPLANLEGGER';
export const SYKMELDINGER = 'SYKMELDINGER';
export const SYKEPENGESOKNADER = 'SYKEPENGESOKNADER';
export const OPPFOELGINGSPLANER = 'OPPFOELGINGSPLANER';
export const HISTORIKK = 'HISTORIKK';
export const VEDTAK = 'VEDTAK';
