export const MOETEPLANLEGGER = "MOETEPLANLEGGER";
export const NOKKELINFORMASJON = "NOKKELINFORMASJON";
export const SYKMELDINGER = "SYKMELDINGER";
export const SYKEPENGESOKNADER = "SYKEPENGESOKNADER";
export const OPPFOELGINGSPLANER = "OPPFOELGINGSPLANER";
export const HISTORIKK = "HISTORIKK";
export const VEDTAK = "VEDTAK";
