export const AKTIVITET_IKKE_MULIG = "AKTIVITET_IKKE_MULIG";
export const AVVENTENDE = "AVVENTENDE";
export const BEHANDLINGSDAGER = "BEHANDLINGSDAGER";
export const GRADERT = "GRADERT";
export const REISETILSKUDD = "REISETILSKUDD";
