export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';
export const HENTER_LEDERE = 'HENTER_LEDERE';
export const LEDERE_HENTET = 'LEDERE_HENTET';
export const HENT_LEDERE_FEILET = 'HENT_LEDERE_FEILET';

export const HENT_NAVBRUKER_FORESPURT = 'HENT_NAVBRUKER_FORESPURT';
export const HENTER_NAVBRUKER = 'HENTER_NAVBRUKER';
export const NAVBRUKER_HENTET = 'NAVBRUKER_HENTET';
export const HENT_NAVBRUKER_FEILET = 'HENT_NAVBRUKER_FEILET';

export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVBRUKER_FORESPURT = 'HENT_AKTIVBRUKER_FORESPURT';
export const HENTER_AKTIVBRUKER = 'HENTER_AKTIVBRUKER';
export const HENT_AKTIVBRUKER_FEILET = 'HENT_AKTIVBRUKER_FEILET';
export const AKTIVBRUKER_HENTET = 'AKTIVBRUKER_HENTET';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';

export const HENT_VEILEDEROPPGAVER_FORESPURT = 'HENT_VEILEDEROPPGAVER_FORESPURT';
export const HENTER_VEILEDEROPPGAVER = 'HENTER_VEILEDEROPPGAVER';
export const HENT_VEILEDEROPPGAVER_FEILET = 'HENT_VEILEDEROPPGAVER_FEILET';
export const VEILEDEROPPGAVER_HENTET = 'VEILEDEROPPGAVER_HENTET';

export const HENT_OPPFOELGINGSDIALOGER_FEILET = 'HENT_OPPFOELGINGSDIALOGER_FEILET';
export const HENTER_OPPFOELGINGSDIALOGER = 'HENTER_OPPFOELGINGSDIALOGER';
export const OPPFOELGINGSDIALOGER_HENTET = 'OPPFOELGINGSDIALOGER_HENTET';
export const HENT_OPPFOELGINGSDIALOGER_FORESPURT = 'HENT_OPPFOELGINGSDIALOGER_FORESPURT';

export const BEHANDLE_OPPGAVE_FORESPURT = 'BEHANDLE_OPPGAVE_FORESPURT';
export const BEHANDLER_OPPGAVE = 'BEHANDLER_OPPGAVE';
export const OPPGAVE_BEHANDLET = 'OPPGAVE_BEHANDLET';
export const ALLE_SVAR_MOTTATT_OPPGAVE_BEHANDLET = 'ALLE_SVAR_MOTTATT_OPPGAVE_BEHANDLET';
export const BEHANDLE_OPPGAVE_FEILET = 'BEHANDLE_OPPGAVE_FEILET';

export const HENT_BEKREFT_MOTE_ARBEIDSGIVEREPOSTINNHOLD_FORESPURT = 'HENT_BEKREFT_MOTE_ARBEIDSGIVEREPOSTINNHOLD_FORESPURT';
export const HENTER_ARBEIDSGIVEREPOSTINNHOLD = 'HENTER_ARBEIDSGIVEREPOSTINNHOLD';
export const ARBEIDSGIVEREPOSTINNHOLD_HENTET = 'ARBEIDSGIVEREPOSTINNHOLD_HENTET';
export const HENT_ARBEIDSGIVEREPOSTINNHOLD_FEILET = 'HENT_ARBEIDSGIVEREPOSTINNHOLD_FEILET';

export const OPPRETT_MOTE_FORESPURT = 'OPPRETT_MOTE_FORESPURT';
export const OPPRETTER_MOTE = 'OPPRETTER_MOTE';
export const MOTE_OPPRETTET = 'MOTE_OPPRETTET';
export const OPPRETT_MOTE_FEILET = 'OPPRETT_MOTE_FEILET';
export const HENT_MOTER_FORESPURT = 'HENT_MOTER_FORESPURT';
export const HENTER_MOTER = 'HENTER_MOTER';
export const MOTER_HENTET = 'MOTER_HENTET';
export const HENT_MOTER_FEILET = 'HENT_MOTER_FEILET';
export const HENT_MOTER_IKKE_TILGANG = 'HENT_MOTER_IKKE_TILGANG';
export const AVBRYT_MOTE_FORESPURT = 'AVBRYT_MOTE_FORESPURT';
export const MOTE_AVBRUTT = 'MOTE_AVBRUTT';
export const AVBRYT_MOTE_FEILET = 'AVBRYT_MOTE_FEILET';
export const AVBRYTER_MOTE = 'AVBRYTER_MOTE';
export const BEKREFT_MOTE_FORESPURT = 'BEKREFT_MOTE_FORESPURT';
export const BEKREFTER_MOTE = 'BEKREFTER_MOTE';
export const MOTE_BEKREFTET = 'MOTE_BEKREFTET';
export const BEKREFT_MOTE_FEILET = 'BEKREFT_MOTE_FEILET';

export const HENT_VIRKSOMHET_FORESPURT = 'HENT_VIRKSOMHET_FORESPURT';
export const HENTER_VIRKSOMHET = 'HENTER_VIRKSOMHET';
export const VIRKSOMHET_HENTET = 'VIRKSOMHET_HENTET';
export const HENT_VIRKSOMHET_FEILET = 'HENT_VIRKSOMHET_FEILET';

export const FLERE_ALTERNATIV = 'FLERE_ALTERNATIV';
export const FJERN_ALTERNATIV = 'FJERN_ALTERNATIV';
export const AVBRYT_FLERE_ALTERNATIV = 'AVBRYT_FLERE_ALTERNATIV';
export const OPPRETTER_FLERE_ALTERNATIV = 'OPPRETTER_FLERE_ALTERNATIV';
export const OPPRETT_FLERE_ALTERNATIV_FORESPURT = 'OPPRETT_FLERE_ALTERNATIV_FORESPURT';
export const OPPRETT_FLERE_ALTERNATIV_FEILET = 'OPPRETT_FLERE_ALTERNATIV_FEILET';
export const OPPRETT_FLERE_ALTERNATIV_BEKREFTET = 'OPPRETT_FLERE_ALTERNATIV_BEKREFTET';
export const VIS_FLERE_ALTERNATIV = 'VIS_FLERE_ALTERNATIV';

export const HENT_FASTLEGER_FORESPURT = 'HENT_FASTLEGER_FORESPURT';
export const HENTER_FASTLEGER = 'HENTER_FASTLEGER';
export const HENT_FASTLEGER_FEILET = 'HENT_FASTLEGER_FEILET';
export const FASTLEGER_HENTET = 'FASTLEGER_HENTET';
export const FASTLEGER_IKKE_FUNNET = 'FASTLEGER_IKKE_FUNNET';

export const HENT_SYKEFORLOEP_FORESPURT = 'HENT_SYKEFORLOEP_FORESPURT';
export const HENTER_SYKEFORLOEP = 'HENTER_SYKEFORLOEP';
export const SYKEFORLOEP_HENTET = 'SYKEFORLOEP_HENTET';
export const HENT_SYKEFORLOEP_FEILET = 'HENT_SYKEFORLOEP_FEILET';

export const HENTER_LEDETEKSTER = 'HENTER_LEDETEKSTER';
export const LEDETEKSTER_HENTET = 'LEDETEKSTER_HENTET';
export const HENT_LEDETEKSTER_FEILET = 'HENT_LEDETEKSTER_FEILET';
export const HENT_LEDETEKSTER_FORESPURT = 'HENT_LEDETEKSTER_FORESPURT';

export const SJEKKER_TILGANG = 'SJEKKER_TILGANG';
export const HAR_TILGANG = 'HAR_TILGANG';
export const HAR_IKKE_TILGANG = 'HAR_IKKE_TILGANG';
export const SJEKK_TILGANG_FEILET = 'SJEKK_TILGANG_FEILET';
export const SJEKK_TILGANG_FORESPURT = 'SJEKK_TILGANG_FORESPURT';

export const SOKNADER_HENTET = 'SOKNADER_HENTET';
export const HENTER_SOKNADER = 'HENTER_SOKNADER';
export const HENT_SOKNADER_FEILET = 'HENT_SOKNADER_FEILET';
export const HENT_SOKNADER_FORESPURT = 'HENT_SOKNADER_FORESPURT';

export const HENT_SYKMELDINGER_FEILET = 'HENT_SYKMELDINGER_FEILET';
export const HENTER_SYKMELDINGER = 'HENTER_SYKMELDINGER';
export const SYKMELDINGER_SORTERT = 'SYKMELDINGER_SORTERT';
export const HENT_SYKMELDINGER_FORESPURT = 'HENT_SYKMELDINGER_FORESPURT';
export const SYKMELDINGER_HENTET = 'SYKMELDINGER_HENTET';
