export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';

export const SJEKK_TILGANG_MOTEADMIN_FORESPURT = 'SJEKK_TILGANG_MOTEADMIN_FORESPURT';
export const HENT_NAVBRUKER_FORESPURT = 'HENT_NAVBRUKER_FORESPURT';

export const HENT_TIDSLINJER_FEILET = 'HENT_TIDSLINJER_FEILET';
export const HENTER_TIDSLINJER = 'HENTER_TIDSLINJER';
export const SET_TIDSLINJER = 'SET_TIDSLINJER';
export const HENT_TIDSLINJER_FORESPURT = 'HENT_TIDSLINJER_FORESPURT';
export const HENT_TIDSLINJER_IKKE_TILGANG = 'HENT_TIDSLINJER_IKKE_TILGANG';

export const HENT_MODIACONTEXT_FORESPURT = 'HENT_MODIACONTEXT_FORESPURT';
export const HENTER_MODIACONTEXT = 'HENTER_MODIACONTEXT';
export const HENT_MODIACONTEXT_FEILET = 'HENT_MODIACONTEXT_FEILET';
export const MODIACONTEXT_HENTET = 'MODIACONTEXT_HENTET';

export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVBRUKER_FORESPURT = 'HENT_AKTIVBRUKER_FORESPURT';
export const HENTER_AKTIVBRUKER = 'HENTER_AKTIVBRUKER';
export const HENT_AKTIVBRUKER_FEILET = 'HENT_AKTIVBRUKER_FEILET';
export const AKTIVBRUKER_HENTET = 'AKTIVBRUKER_HENTET';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';
