export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';
export const HENTER_LEDERE = 'HENTER_LEDERE';
export const HENT_LEDERE_IKKE_TILGANG = 'HENT_LEDERE_IKKE_TILGANG';
export const LEDERE_HENTET = 'LEDERE_HENTET';
export const HENT_LEDERE_FEILET = 'HENT_LEDERE_FEILET';

export const HENT_NAVBRUKER_FORESPURT = 'HENT_NAVBRUKER_FORESPURT';

export const HENT_TIDSLINJER_FEILET = 'HENT_TIDSLINJER_FEILET';
export const HENTER_TIDSLINJER = 'HENTER_TIDSLINJER';
export const SET_TIDSLINJER = 'SET_TIDSLINJER';
export const HENT_TIDSLINJER_FORESPURT = 'HENT_TIDSLINJER_FORESPURT';
export const HENT_TIDSLINJER_IKKE_TILGANG = 'HENT_TIDSLINJER_IKKE_TILGANG';

export const PUSH_MODIACONTEXT_FORESPURT = 'PUSH_MODIACONTEXT_FORESPURT';
export const PUSH_MODIACONTEXT_FEILET = 'PUSH_MODIACONTEXT_FEILET';
export const MODIACONTEXT_PUSHET = 'MODIACONTEXT_PUSHET';
export const PUSHER_MODIACONTEXT = 'PUSHER_MODIACONTEXT';

export const HENT_AKTIVBRUKER_FORESPURT = 'HENT_AKTIVBRUKER_FORESPURT';
export const HENTER_AKTIVBRUKER = 'HENTER_AKTIVBRUKER';
export const HENT_AKTIVBRUKER_FEILET = 'HENT_AKTIVBRUKER_FEILET';
export const AKTIVBRUKER_HENTET = 'AKTIVBRUKER_HENTET';

export const HENT_AKTIVENHET_FORESPURT = 'HENT_AKTIVENHET_FORESPURT';
export const HENTER_AKTIVENHET = 'HENTER_AKTIVENHET';
export const HENT_AKTIVENHET_FEILET = 'HENT_AKTIVENHET_FEILET';
export const AKTIVENHET_HENTET = 'AKTIVENHET_HENTET';

export const HENT_VEILEDEROPPGAVER_FORESPURT = 'HENT_VEILEDEROPPGAVER_FORESPURT';
export const HENTER_VEILEDEROPPGAVER = 'HENTER_VEILEDEROPPGAVER';
export const HENT_VEILEDEROPPGAVER_FEILET = 'HENT_VEILEDEROPPGAVER_FEILET';
export const VEILEDEROPPGAVER_HENTET = 'VEILEDEROPPGAVER_HENTET';

export const HENT_BEHANDLENDE_ENHET_FORESPURT = 'HENT_BEHANDLENDE_ENHET_FORESPURT';
export const HENTER_BEHANDLENDE_ENHET = 'HENTER_BEHANDLENDE_ENHET';
export const HENT_BEHANDLENDE_ENHET_FEILET = 'HENT_BEHANDLENDE_ENHET_FEILET';
export const BEHANDLENDE_ENHET_HENTET = 'BEHANDLENDE_ENHET_HENTET';

export const HENT_DOKUMENTINFO_FORESPURT = 'HENT_DOKUMENTINFO_FORESPURT';
export const HENTER_DOKUMENTINFO = 'HENTER_DOKUMENTINFO';
export const HENT_DOKUMENTINFO_FEILET = 'HENT_DOKUMENTINFO_FEILET';
export const DOKUMENTINFO_HENTET = 'DOKUMENTINFO_HENTET';

export const HENT_OPPFOELGINGSDIALOGER_FEILET = 'HENT_OPPFOELGINGSDIALOGER_FEILET';
export const HENTER_OPPFOELGINGSDIALOGER = 'HENTER_OPPFOELGINGSDIALOGER';
export const OPPFOELGINGSDIALOGER_HENTET = 'OPPFOELGINGSDIALOGER_HENTET';
export const HENT_OPPFOELGINGSDIALOGER_IKKE_TILGANG = 'HENT_OPPFOELGINGSDIALOGER_IKKE_TILGANG';
export const HENT_OPPFOELGINGSDIALOGER_FORESPURT = 'HENT_OPPFOELGINGSDIALOGER_FORESPURT';

export const BEHANDLE_OPPGAVE_FORESPURT = 'BEHANDLE_OPPGAVE_FORESPURT';
export const BEHANDLER_OPPGAVE = 'BEHANDLER_OPPGAVE';
export const OPPGAVE_BEHANDLET = 'OPPGAVE_BEHANDLET';
export const BEHANDLE_OPPGAVE_FEILET = 'BEHANDLE_OPPGAVE_FEILET';
