export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';

export const SJEKK_TILGANG_MOTEADMIN_FORESPURT = 'SJEKK_TILGANG_MOTEADMIN_FORESPURT';
export const HENT_NAVBRUKER_FORESPURT = 'HENT_NAVBRUKER_FORESPURT';

export const HENT_TIDSLINJER_FEILET = 'HENT_TIDSLINJER_FEILET';
export const HENTER_TIDSLINJER = 'HENTER_TIDSLINJER';
export const SET_TIDSLINJER = 'SET_TIDSLINJER';
export const HENT_TIDSLINJER_FORESPURT = 'HENT_TIDSLINJER_FORESPURT';
export const HENT_TIDSLINJER_IKKE_TILGANG = 'HENT_TIDSLINJER_IKKE_TILGANG';

export const HENT_SYKMELDINGER_FEILET = 'HENT_SYKMELDINGER_FEILET';
export const HENTER_SYKMELDINGER = 'HENTER_SYKMELDINGER';
export const SYKMELDINGER_HENTET = 'SYKMELDINGER_HENTET';
export const HENT_SYKMELDINGER_FORESPURT = 'HENT_SYKMELDINGER_FORESPURT';
export const HENT_SYKMELDINGER_IKKE_TILGANG = 'HENT_SYKMELDINGER_IKKE_TILGANG';
