export const FASTLEGEREST_ROOT = "/fastlegerest/api/internad/fastlege/v1";
export const ISDIALOGMOTE_ROOT = "/isdialogmote/api/v1";
export const ISPENGESTOPP_ROOT = "/ispengestopp/api/v1";
export const ISPERSONOPPGAVE_ROOT = "/ispersonoppgave/api/v1";
export const ISPREDIKSJON_ROOT = "/isprediksjon/api/v1";
export const MODIACONTEXTHOLDER_ROOT = "/modiacontextholder/api";
export const MODIASYFOREST_ROOT = "/modiasyforest/api/internad";
export const SYFOBEHANDLENDEENHET_ROOT = "/syfobehandlendeenhet/api/internad";
export const SYFOMOTEADMIN_ROOT = "/syfomoteadmin/api/internad";
export const SYFOMOTEBEHOV_ROOT = "/syfomotebehov/api/internad/veileder";
export const SYFOOPPFOLGINGSPLANSERVICE_ROOT =
  "/syfooppfolgingsplanservice/api/internad";
export const SYFOPERSON_ROOT = "/syfoperson/api";
export const SYFOSMREGISTER_ROOT = "/syfosmregister/api/v1";
export const SYFOSOKNAD_ROOT = "/syfosoknad/api/veileder/internad";
export const SYFOTILGANGSKONTROLL_ROOT = "/syfo-tilgangskontroll/api";
export const SYFOVEILEDER_ROOT = "/syfoveileder/api/v1";
export const VEDTAK_ROOT = "/veileder/vedtak";
export const UNLEASH_ROOT = "/isenabled";
